# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True)),
                ('received_from', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
