# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
