# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180601_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='main.Person'),
        ),
    ]
