# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180606_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
