# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_made',
        ),
    ]
